[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "openzeppelin-contracts-upgradeable/=node_modules/eigenlayer/lib/openzeppelin-contracts-upgradeable/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/"
]

[rpc_endpoints]
sonic = "https://rpc.soniclabs.com"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
